export const ACTIONS = {
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_ERROR : "GET_ERROR",
    GET_SEARCH : "GET_SEARCH",
    ADD_PRODUCT: "ADD_PRODUCT",
    GET_INCREASE :'GET_INCREASE',
    GET_DECREASE : "GET_DCREASE",
    GET_REMOVE: "GET_REMOVE"
}